=== filipejsfreitas/DAW2020/tp2/ProjectRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="projectrecord">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="keyname"/>
        <xs:element ref="title"/>
        <xs:element minOccurs="0" ref="subtitle"/>
        <xs:element ref="begindate"/>
        <xs:element ref="enddate"/>
        <xs:element ref="supervisor"/>
        <xs:element ref="workteam"/>
        <xs:element ref="abstract"/>
        <xs:element ref="deliverables"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="keyname" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="begindate" type="xs:string"/>
  <xs:element name="enddate" type="xs:string"/>
  <xs:element name="supervisor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="workteam">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="member"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="abstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deliverables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="deliverable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="link">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.link"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.link">
    <xs:attribute name="href" use="required"/>
  </xs:attributeGroup>
  <xs:element name="member">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="email"/>
        <xs:element minOccurs="0" ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="b"/>
        <xs:element ref="u"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="deliverable">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="id" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="b"/>
        <xs:element ref="u"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="u"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="b"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== filipejsfreitas/DAW2020/tp2/TP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<projectrecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ProjectRecord.xsd">
    <keyname>DAW2020:TP2</keyname>
    <title>Trabalho Prático 2: Criação de um DTD para Project Records</title>
    <begindate>2020-10-21</begindate>
    <enddate>2020-10-27</enddate>
    <supervisor>
        <link href="http://www.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </link>
    </supervisor>
    <workteam>
        <member>
            <id>PG42828</id>
            <name>Filipe Freitas</name>
            <email>pg42828@alunos.uminho.pt</email>
        </member>
    </workteam>
    <abstract>
        <p>
            O segundo trabalho da UC de Desenvolvimento de Aplicações Web (TP2) consiste na criação de um DTD para descrever a estrutura de ficheiros XML que serão "<b>Project Records</b>".
        </p>
        <p>
            Um <b>Project Record</b> é um documento breve que descreve o enunciado, objetivos, prazos, e elementos do grupo de trabalho de um projeto. Existirá um <b>Project Record</b>
            para cada um dos projetos elaborados no decurso da UC.
        </p>
        <p>
            Após a elaboração do DTD dos <b>Project Records</b>, deverá ser criado um <b>Project Record</b> relativo à elaboração desse mesmo DTD.
        </p>
    </abstract>
    <deliverables>
        <deliverable>
            <link href="ProjectRecord.dtd">
                ProjectRecord.dtd - DTD descrevendo a estrutura de um Project Record
            </link>
        </deliverable>
        <deliverable>
            <link href="TP2.xml">
                TP2.xml - XML do Project Record relativo à criação do DTD
            </link>
        </deliverable>
    </deliverables>
</projectrecord>
